### ISSUE TITLE
Use babel-preset-env

### ISSUE THREAD

**Issue by kevin940726** [17media/node-logger#1]
[`babel-preset-env`](https://github.com/babel/babel-preset-env) has option to compile to node-6 compatible. Is there any reason we should use `node-6` instead?

**Comment by kevin940726** [comment]
Another question, why should we use `module.exports` if we already have `export` statement support?

**Comment by boczeratul** [comment]
changed to `export`

**Comment by boczeratul** [comment]
changed to `babel-preset-env`
I wasn't familiar with the presets, thanks for the info 👍
